# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chronologic}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Raymond"]
  s.date = %q{2010-08-27}
  s.description = %q{Chronologic is a library for managing Activity Streams (aka News Feeds or Timelines). Like Twitter, or just about any social network. It uses Cassandra.}
  s.email = %q{sco@gowalla.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "config.ru",
     "examples/gowalla.rb",
     "examples/gowalla_activerecord.rb",
     "examples/twitter.rb",
     "init.rb",
     "lib/chronologic.rb",
     "lib/chronologic/client.rb",
     "lib/chronologic/connection.rb",
     "lib/chronologic/railtie.rb",
     "lib/chronologic/server-async.rb",
     "lib/chronologic/server.rb",
     "lib/chronologic/version.rb",
     "test/chronologic_connection_spec.rb",
     "test/helper.rb",
     "test/spec_helper.rb",
     "test/test_chronologic.rb"
  ]
  s.homepage = %q{http://github.com/gowalla/chronologic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Activity feeds as a service.}
  s.test_files = [
    "test/chronologic_connection_spec.rb",
     "test/helper.rb",
     "test/spec_helper.rb",
     "test/test_chronologic.rb",
     "examples/gowalla.rb",
     "examples/gowalla_activerecord.rb",
     "examples/twitter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-http-persistent>, [">= 1.2.4"])
      s.add_runtime_dependency(%q<cassandra>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<net-http-persistent>, [">= 1.2.4"])
      s.add_dependency(%q<cassandra>, [">= 0.9.0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-http-persistent>, [">= 1.2.4"])
    s.add_dependency(%q<cassandra>, [">= 0.9.0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

